# SPDX-FileCopyrightText: The terraform-provider-k8s Authors
# SPDX-License-Identifier: 0BSD

name: NetworkingIstioIoGatewayV1Beta1Resource
on:
  pull_request:
    branches: [ main ]
    paths:
      - examples/resources/k8s_networking_istio_io_gateway_v1beta1/**
      - internal/provider/networking_istio_io_v1beta1/networking_istio_io_gateway_v1beta1_resource.go
      - terratest/networking_istio_io_v1beta1/networking_istio_io_gateway_v1beta1_resource_test.go
jobs:
  terratest:
    name: Test with Terraform ${{ matrix.terraform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        terraform:
          - 1.4.*
          - 1.5.*
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup_go
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - id: setup_terraform
        name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - id: install
        name: Install Provider
        run: make install
      - id: terratest
        name: Run Terratest Tests
        run: go test -v -timeout=120s -count=1 -tags testing -run TestNetworkingIstioIoGatewayV1Beta1Resource ./terratest/networking_istio_io_v1beta1
